import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Page from "./joke/[category]";
import Link from "next/link";
const Home: NextPage = (props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/joke/animal">
        <a>Animal</a>
      </Link>
      <Link href="/joke/career">
        <a>Career</a>
      </Link>
      <Link href="/joke/celebrity">
        <a>celebrity</a>
      </Link>
      <Link href="/joke/dev">
        <a>dev</a>
      </Link>
      <Link href="/joke/explicit">
        <a>explicit</a>
      </Link>
      <Link href="/joke/fashion">
        <a>fashion</a>
      </Link>
      <Link href="/joke/food">
        <a>food</a>
      </Link>
      <Link href="/joke/history">
        <a>history</a>
      </Link>
      <Link href="/joke/money">
        <a>money</a>
      </Link>
      <Link href="/joke/movie">
        <a>movie</a>
      </Link>
      <Link href="/joke/music">
        <a>music</a>
      </Link>
      <Link href="/joke/political">
        <a>political</a>
      </Link>
      <Link href="/joke/religion">
        <a>religion</a>
      </Link>
      <Link href="/joke/science">
        <a>Science</a>
      </Link>
      <Link href="/joke/sport">
        <a>sport</a>
      </Link>
      <Link href="/joke/travel">
        <a>travel</a>
      </Link>
    </div>
  );
};

export default Home;
